export const CREATED_NEW_ORDER_NOTIFICATION = 'CREATED_NEW_ORDER_NOTIFICATION';
export const CREATE_NEW_CUSTOMER_ACCOUNT_VERIFIFICATION =
  'CREATE_CUSTOMER_ACCOUNT_VERIFIFICATION';
export const ACCOUNT_VERIFICATION_SUCCESS = 'ACCOUNT_VERIFICATION_SUCCESS';
export const RESET_PASSWORD_VERIFICATION = 'RESET_PASSWORD_VERIFICATION';
